version: '3.3'

services:

    ward:
        image: antonyleons/ward
        container_name: ward
        restart: unless-stopped
        ports:
            - '4000:4000'
        environment:
            - WARD_PORT=4000
            - WARD_THEME=dark  #light 
            - WARD_NAME=labarta-server            
        privileged: false  #true
              